### ISSUE TITLE
search-paths for Chez Scheme is not properly set.

### ISSUE THREAD

**Issue by Saigut** [fedeinthemix/chez-srfi#3]
In `srfi/private/include/compat.chezscheme.sls`, search-paths for is set to source-directories, but it should be search path of libraries not sources. So I suggest changing to this:
```
(library (srfi private include compat)
  (export
    search-paths)
  (import
    (rnrs base)
    (only (chezscheme) library-directories))

(define (search-paths)
    (let loop ([pp (library-directories)])
      (if (null? pp)
          '()
          (cons (caar pp) (loop (cdr pp))))))

)
```

**Comment by fedeinthemix** [comment]
Could you please describe the problem you are having, so that I can better
understand what you are trying to fix? If you could give a minimal example
that reproduces the problem, that would be ideal.

The parameter 'source-directories' is not only used for source files. From
the manual:

"source-directories determines the set of directories searched for source or
object files when a file is loaded via load, load-library, load-program,
include, visit,
or revisit, when a syntax error occurs, or when a source file is opened in
the interactive
inspector."

On my system I set the environment variable CHEZSCHEMELIBDIRS to the
directory where I have the compiled srfi libraries (no source files, only
object files) and I can use it without problems.

**Comment by Saigut** [comment]
Hi, I clone the chez-srfi/ and `make build` it, then I set CHEZSCHEMELIBDIRS to `/xxx/chez-srfi:`, it looks nothing wrong when I use srfi in my program. But after I removed all the object files (*.so) in chez-srfi, I run my program again, it will prompt such error:

> Exception in include/resolve: cannot find file in search paths with irritants ("srfi/%3a19/srfi-19.scm" ("/xxx/chez-srfi/srfi/:19" "/xxx/chez-srfi/srfi/:19" "/xxx/chez-srfi/srfi" "/xxx/chez-srfi/srfi" "."))

This shows it search "/xxx/chez-srfi/srfi/:19", "/xxx/chez-srfi/srfi" and "." for "srfi/%3a19/srfi-19.scm", but not search in /xxx/chez-srfi. So it can not find "srfi/%3a19/srfi-19.scm". Then I traced the code, find that it search in `search-paths`, but `search-paths` is `source-directories` of chez scheme. `source-directories` do not include library directories. So I think `search-paths` should defined using `library-directories`.

And you can look at `compat.ikarus.sls`,  `compat.mzscheme.sls` and `compat.ypsilon.sls` in srfi/private/include/, they all define `search-paths` using library directories.

**Comment by fedeinthemix** [comment]
I can reproduce the problem and your suggested solution seems to work.

I've pushed it.
Thanks!
